FROM python:3.9-slim-buster

ENV SERVER_PORT=5555
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV IN_DOCKER_CONTAINER Yes

# install dependencies
RUN apt-get update && apt-get install -y iptables tcpdump iproute2 tmux dnsutils
RUN pip install --upgrade pip
COPY services/serviceB/requirements.txt /tmp/requirements.txt
RUN python3 -m pip install -r /tmp/requirements.txt 

EXPOSE 5556

WORKDIR /app
COPY ./services/serviceB/serviceConfig.ini /app/serviceConfig.ini
COPY ./services/serviceB /app
COPY ./services/shared /app/

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["gunicorn", "--bind", "0.0.0.0:5556", "runserver:app"]